### ISSUE TITLE
fixes for openvz_storage_backends.md 

### ISSUE THREAD

**Issue by CoolCold** [pavel-odintsov/OpenVZ_ZFS#2]
I'm not native language speaker, but from my point of view you should change some words in "openvz_storage_backends.md" like from 'big' to 'large' . In addition, there are a lot of spelling errors/typos (may be ms office license expired?). Screenshot is below.

![Image ms word](http://gyazo.coolcold.org/upload/0057a8547d9464411aa1b69a850d.png)

**Comment by pavel-odintsov** [comment]
Thank you so much :) I fixed almost all typos.  Thanks to https://webmaster.yandex.com/spellcheck.xml :)
